### PR TITLE
Switch force-case-sensitivity-webpack-plugin with case-sensitive-path…

### PR DESCRIPTION
**Pull request by NorwegianKiwi**
…s-webpack-plugin, and use a forked version of it to deal with Norwegian letters.

Before merging this, I want to wait a little bit to see if the PR I submitted to case-sensitive-paths-webpack-plugin goes through; if so I want to update package.json to use the original library.

### CODE REVIEW

**Comment by NorwegianKiwi** [comment]
This deals with issue #64

**Comment by NorwegianKiwi** [comment]
I suggest we just use my fork for now, and then if the PR gets accepted at some point, we will switch to the official version.

**Comment by Urthen** [comment]
Sorry for taking so long!

**Comment by NorwegianKiwi** [comment]
No worries! :)

**Pull request merged**
